Import('qt_env')

env = qt_env.Clone()

env.AppendUnique(CPPDEFINES = [
    'DIAGNOSEBASIC_LIBRARY',
    'NOMINMAX',
    # suppress a few warnings caused by boost vs vc++ paranoia
    '_SCL_SECURE_NO_WARNINGS'
])

# Boost produces very long names with msvc truncates. Doesn't seem to cause
# problems.
env.AppendUnique(CPPFLAGS = [ '-wd4503' ])

env.AppendUnique(CPPPATH = [
    '${BOOSTPATH}'
])

lib = env.SharedLibrary('diagnoseBasic', env.Glob('*.cpp'))
env.InstallModule(lib)

res = env['QT_USED_MODULES']
Return('res')
