name: Build Diagnose Basic

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]

env:
  VCPKG_BINARY_SOURCES: clear;x-azblob,${{ vars.AZ_BLOB_VCPKG_URL }},${{ secrets.AZ_BLOB_SAS }},readwrite

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Build Diagnose Basic
        id: build-diagnose-basic
        uses: ModOrganizer2/build-with-mob-action@master
        with:
          mo2-dependencies: uibase
